"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.appRouterV1 = void 0;
const controllers_1 = require("../../controllers");
const user_router_1 = require("./user-router");
const upload_file_route_1 = require("./upload-file-route");
const myProfileRouter_1 = require("./myProfileRouter");
const productRouter_1 = require("./productRouter");
const orderRouter_1 = require("./orderRouter");
const categoryRouter_1 = require("./categoryRouter");
const addressRouter_1 = require("./addressRouter");
const transactionRoutes_1 = require("./transactionRoutes");
const statisticRouter_1 = require("./statisticRouter");
const cartRouter_1 = require("./cartRouter");
const settingRouter_1 = require("./settingRouter");
const appRouterV1 = (app) => {
    app.get('/api/v1', async (req, res) => await (0, controllers_1.index)(req, res));
    (0, upload_file_route_1.uploadFileRoutes)(app);
    (0, myProfileRouter_1.myProfileRouter)(app);
    (0, user_router_1.userRoutes)(app);
    (0, productRouter_1.productRoutes)(app);
    (0, orderRouter_1.orderRoutes)(app);
    (0, categoryRouter_1.categoryRoutes)(app);
    (0, addressRouter_1.addressRoutes)(app);
    (0, transactionRoutes_1.transactionRoutes)(app);
    (0, statisticRouter_1.statisticRouters)(app);
    (0, cartRouter_1.cartRoutes)(app);
    (0, settingRouter_1.settingRouters)(app);
};
exports.appRouterV1 = appRouterV1;
